service: iampam-crud-service
# custom: null
provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-northeast-2
  iamRoleStatements: # iamRoleStatements : 람다 함수가 AWS S3와 상호 작용하는 데 필요한 권한을 정의
    - Effect: Allow
      Action:
        - s3:*
        - s3-object-lambda:*
      Resource:
        - arn:aws:s3:::iampam-provider/provider/*
functions:
  awsAccount:
    handler: awsAccount.handler
    events:
      - http:
          path: /awsAccount
          method: GET
          cors: true
      - http:
          path: /awsAccount/{awsAccount}
          method: PUT
          cors: true
      - http:
          path: /awsAccount/{awsAccount}
          method: DELETE
          cors: true
      - http:
          path: /awsAccount
          method: POST
          cors: true
  awsCheckRules:
    handler: awsCheckRules.handler
    events:
      - http:
          path: /awscheckrules
          method: GET
          cors: true
      - http:
          path: /awscheckrules/{checkRuleName}
          method: PUT
          cors: true
      - http:
          path: /awscheckrules/{checkRuleName}
          method: DELETE
          cors: true
      - http:
          path: /awscheckrules
          method: POST
          cors: true
  awsProducts:
    handler: awsProducts.handler
    events:
      - http:
          path: /awsproducts
          method: GET
          cors: true
      - http:
          path: /awsproducts/{awsResourceType}
          method: PUT
          cors: true
      - http:
          path: /awsproducts/{awsResourceType}
          method: DELETE
          cors: true
      - http:
          path: /awsproducts
          method: POST
          cors: true
  awsRegions:
    handler: awsRegions.handler
    events:
      - http:
          path: /awsregions
          method: GET
          cors: true
      - http:
          path: /awsregions/{awsRegionCode}
          method: PUT
          cors: true
      - http:
          path: /awsregions/{awsRegionCode}
          method: DELETE
          cors: true
      - http:
          path: /awsregions
          method: POST
          cors: true
  socialUsers:
    handler: socialUsers.handler
    events:
      - http:
          path: /socialusers
          method: GET
          cors: true
      - http:
          path: /socialusers/{socialEmail}
          method: PUT
          cors: true
      - http:
          path: /socialusers/{socialEmail}
          method: DELETE
          cors: true
      - http:
          path: /socialusers
          method: POST
          cors: true
  tenants:
    handler: tenants.handler
    events:
      - http:
          path: /tenants
          method: GET
          cors: true
      - http:
          path: /tenants/{companyRegistrationNumber}
          method: PUT
          cors: true
      - http:
          path: /tenants/{companyRegistrationNumber}
          method: DELETE
          cors: true
      - http:
          path: /tenants
          method: POST
          cors: true
package:
  include:
    - common.js
